etcd election timout 설정 추가
openinfradev/helm-charts pull request #21
Opened 2021-03-24 02:19 UTC by zugwan

느린 디스크 등의 문제로 etcd 리더 변경이 자주 발생하는 환경에서 timeout 값 (기본: 1000ms -> 예: 10000) 증가시키면 문제 상황을 완화할 수 있습니다. 이를 설정하는 변수를 추가하였습니다.

2021-03-24 05:44 UTC, robertchoi80 commented on cluster-api-openstack/Chart.lock
> +dependencies:
helm-toolkit 은 어떤 library 때문에 사용되는 건가요?

2021-03-25 00:24 UTC, zugwan commented on cluster-api-openstack/Chart.lock
> +dependencies:
아래처럼 ini 형식으로 파일 내용 생성하는 용도로 사용하고 있습니다.
`    - content: {{ include "helm-toolkit.utils.to_ini" .Values.openstack.cloud.conf | b64enc }}`
https://github.com/openinfradev/taco-helm/blob/89db5eda632a761cfd9aa15683b09e91e7ce01fd/cluster-api-openstack/templates/kubeadm-control-plane.yaml#L37

2021-03-25 06:14 UTC, Jaesang requested changes
helm install시 chart폴더가 없다는 에러가 나는데, 폴더에서 helm dep update를 해서 charts폴더에 helm-toolkit 차트가 있어야 Install이 됩니다.
```
$ helm install cluster-jaesang ./cluster-api-openstack -f values-override.yaml
Error: found in Chart.yaml, but missing in charts/ directory: helm-toolkit
```

2021-03-25 06:14 UTC, Jaesang commented on cluster-api-openstack/values.yaml
> +   election_timeout: 1000
띄어쓰기가 한칸 더 들어가있네요

2021-03-25 08:15 UTC, Jaesang commented on cluster-api-openstack/values.yaml
> +   election_timeout: 1000
최대값은 50000입니다.

2021-03-26 00:53 UTC, zugwan commented on cluster-api-openstack/values.yaml
> +   election_timeout: 1000
아래 내용 반영하였습니다.
1. helm-toolkit 차트를 포함하였습니다.
2. 들여쓰기 수정했습니다.
etcd_timeout 변수 값은 etcd의 관련 설정 값과 동일하게 해두었습니다.

2021-03-30 05:45 UTC, zugwan commented
> 
> 
> helm install시 chart폴더가 없다는 에러가 나는데, 폴더에서 helm dep update를 해서 charts폴더에 helm-toolkit 차트가 있어야 Install이 됩니다.
> 
> ```
> $ helm install cluster-jaesang ./cluster-api-openstack -f values-override.yaml
> Error: found in Chart.yaml, but missing in charts/ directory: helm-toolkit
> ```

수정 내용 반영 후 코멘트를 남기었다고 생각했는데 최종 제출을 안한 듯 하네요.

chats/ 디렉토리를 포함하여 반영하였습니다.

2021-03-30 06:56 UTC, jabbukka approved these changes

2021-03-30 07:22 UTC, Jaesang approved these changes

2021-03-30 07:23 UTC, merged