use 'yq v4' to create a cloud secret
openinfradev/helm-charts pull request #22
Opened 2021-03-30 06:09 UTC by zugwan

OpenStack 클라우드 (clouds.yaml) Secret을 생성하는 스크립트에서 사용하는 yq(https://mikefarah.github.io/yq/) 버전을 v4로 변경
- yq는 v3와 v4의 명령어 문법이 상이
- v3는 21년 8월 지원 중단 예정

2021-03-30 06:15 UTC, jabbukka approved these changes

2021-03-30 06:35 UTC, intelliguy approved these changes

2021-03-30 07:22 UTC, Jaesang requested changes
yq v4에서만 정상동작한다는 안내가 추가되어야할 것 같습니다.

2021-03-31 01:33 UTC, zugwan commented
> yq v4에서만 정상동작한다는 안내가 추가되어야할 것 같습니다.

yq 버전 체크해서 v3인 경우 에러 메세지 발생하도록 수정하였습니다.

2021-03-31 07:37 UTC, Jaesang approved these changes

2021-03-31 07:42 UTC, merged