renamed hanu-helm-repo to helm-repo
openinfradev/helm-charts pull request #36
Opened 2021-05-13 08:12 UTC by jabbukka

* hanu-helm-repo 를 helm-repo로 명칭 변경

2021-05-13 08:16 UTC, zugwan approved these changes

2021-05-13 08:19 UTC, zugwan requested changes

2021-05-13 08:19 UTC, zugwan commented on .github/workflows/publish.yaml
> +          charts_url:  https://openinfradev.github.io/helm-charts
helm-repo 가 맞는 변경으로 보입니다.

2021-05-13 08:19 UTC, zugwan commented on .github/workflows/publish.yaml
> +          repository: helm-charts
helm-repo 가 맞는 변경으로 보입니다.

2021-05-14 01:15 UTC, jabbukka commented on .github/workflows/publish.yaml
> +          charts_url:  https://openinfradev.github.io/helm-charts
수정하였습니다.

2021-05-14 01:15 UTC, jabbukka commented on .github/workflows/publish.yaml
> +          repository: helm-charts
수정하였습니다.

2021-05-14 01:16 UTC, zugwan approved these changes

2021-05-14 01:38 UTC, robertchoi80 approved these changes

2021-05-14 01:38 UTC, merged