Upgrade Argo to v2.12.5
openinfradev/helm-charts pull request #4
Opened 2021-01-22 06:37 UTC by jabbukka

2021-01-22 07:07 UTC, zugwan approved these changes
LGTM

2021-01-22 07:19 UTC, bluejayKR requested changes
v2.12.5로 업그레이드 하는 이유가 PR 메세지에 나와야 할 것 같습니다. 
어떤 문제에 대한 Fix가 있다던지, 혹은 우리에게 필요한 기능이 추가되었다던지 등.

2021-01-25 01:13 UTC, jabbukka commented
@bluejayKR 네 이슈에 추가 코멘트 작성하였습니다.

2021-01-25 02:23 UTC, bluejayKR approved these changes

2021-01-25 02:41 UTC, merged