Added new chart for cluster api provider aws
openinfradev/helm-charts pull request #46
Opened 2021-06-29 06:38 UTC by jabbukka

* cluster-api-provider-aws를 위한 helm chart
* machineDeployment 혹은 machinePool을 이용해서 배포할 수 있다. (둘 중 하나 선택하여 사용해야 함)
* `machinePool.enabled` 를 `false`로 설정하면 machineDeployment로 배포

2021-06-30 08:38 UTC, zugwan requested changes

2021-06-30 08:38 UTC, zugwan commented on cluster-api-aws/templates/machine-pool.yaml
> +  {{- with .Values.cluster.networkSpec.subnets }}
.Values.machinePool.subnets 이 values.yaml에는 존재하는데 현재 값이 맞다면 values.yaml 내용은 제거하는 것이 좋겠습니다. 그리고 subnets 변수 정의를 명시적으로 해주어야 하나요? 추가 변수 오버라이딩 없이 배포하면 machinepool subnet 이 없다는 오류가 발생해서 문의를 드립니다.

2021-06-30 09:04 UTC, jabbukka commented on cluster-api-aws/templates/machine-pool.yaml
> +  {{- with .Values.cluster.networkSpec.subnets }}
.Values.machinePool.subnets을 사용하도록 수정하였습니다.

`AWSMachinePool`의 subnets은 명시적으로 넣어줘야합니다. vpc 및 네트워크 설정을 미리 만들어 놓은 상태에서는 값을 설정하는데 문제가 없겠지만, 
만약 vpc를 새롭게 만들면서 AWSMachinePool로 배포하시려면, vpc subnet들이 만들어지는 순간 AWSMachinePool의 subnets 값들을 세팅해줘야합니다.

2021-07-01 01:00 UTC, zugwan commented on cluster-api-aws/templates/machine-pool.yaml
> +  {{- with .Values.cluster.networkSpec.subnets }}
CAPA 컨트롤러에서 자동으로 선택할 수 있도록 할 수 도 있을 듯 한데, 이건 CAPA 구현 문제이니 이해했습니다.

2021-07-01 01:02 UTC, zugwan requested changes

2021-07-01 01:02 UTC, zugwan commented on cluster-api-aws/templates/aws-cluster.yaml
> +  {{- end }}
bastion 호스트 사용 유무도 설정하면 좋을 듯 합니다.
https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/522cd0fe148bd08d9a388ec53a4a6e5fce20c90f/config/crd/bases/infrastructure.cluster.x-k8s.io_awsclusters.yaml#L72

2021-07-01 01:49 UTC, jabbukka commented on cluster-api-aws/templates/aws-cluster.yaml
> +  {{- end }}
설정 추가하였습니다.

2021-07-02 02:02 UTC, jabbukka commented
`AWSMachine` Spec: https://cluster-api-aws.sigs.k8s.io/crd/experimental.html#infrastructure.cluster.x-k8s.io/v1alpha4.AWSMachinePoolSpec

2021-07-02 03:08 UTC, zugwan commented
> `AWSMachine` Spec: https://cluster-api-aws.sigs.k8s.io/crd/experimental.html#infrastructure.cluster.x-k8s.io/v1alpha4.AWSMachinePoolSpec

이 문서에서는 subnets이 optional 이네요. :confused:

2021-07-02 04:30 UTC, zugwan approved these changes

2021-07-02 08:46 UTC, intelliguy commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
아래 template이 있는데 명시적으로 얘를 만들어주는 이유는 뭘까요?

2021-07-02 08:49 UTC, jabbukka commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
KubeadmConfigTemplate 말씀하시는걸까요?
KubeadmConfigTemplate은 MachineDeployment를 사용할 때만 필요한 설정입니다. KubeadmConfig는 control plane이 사용하는 Config입니다.

2021-07-02 09:16 UTC, intelliguy commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
전체를 살펴보니 MachinePool에 연결되어 사용하는 것 같네요.
MachinePool는  KubeadmConfigTemplate 를 통해 자동 생성이 안되서 이렇게 처리하는 것이겠죠?

2021-07-02 09:27 UTC, jabbukka commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
네 MachinePool의 ConfigRef는 KubeadmConfig 타입을 써야하는 것 같습니다. clusterctl config로 만들어주는 manifest를 기반으로 작업하였는데 MachinePool는 KubeadmConfig를 사용하고 있습니다.

2021-07-05 02:59 UTC, seungkyua commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
MachinePool을 사용하지 않는다면 KubeadmConfig는 생성할 필요가 없을 것 같습니다. 무조건 생성하는 것으로 되어 있네요.

2021-07-05 04:31 UTC, jabbukka commented on cluster-api-aws/templates/kubeadm-config.yaml
> +kind: KubeadmConfig
@seungkyua if문으로 machinepool 사용시에만 만들어지도록 수정하였습니다.

2021-07-05 05:04 UTC, intelliguy approved these changes

2021-07-05 05:27 UTC, robertchoi80 commented on cluster-api-aws/templates/machine-pool.yaml
> +  - {{ .Values.cluster.region }}
(제가 잘 몰라서,,)  여기에 az 이름들을 array로 넣지 않고 region 값만 넣으면 되는 것인가요??

2021-07-05 05:34 UTC, jabbukka commented on cluster-api-aws/templates/machine-pool.yaml
> +  - {{ .Values.cluster.region }}
넵 예제에서도 region만 넣더라구요. 실제로 사용할 AZ 리스트에 대해서는 밑에 있는 `subnets`을 통해 정할 수 있습니다.

2021-07-05 05:36 UTC, robertchoi80 commented on cluster-api-aws/templates/machine-pool.yaml
> +  - {{ .Values.cluster.region }}
넵!

2021-07-05 05:41 UTC, robertchoi80 approved these changes

2021-07-05 05:51 UTC, merged