add 'eck-resource' helm chart.
openinfradev/helm-charts pull request #6
Opened 2021-01-27 01:03 UTC by jabbukka

### Issue
https://github.com/openinfradev/decapod-base-yaml/issues/23

### Description
* elastic 공식 차트인 eck-operator를 사용하기로 함.
* eck-operator는 operator를 설치해주지만 custom resource(elasticsearch, kibana 등)을 만들진 않음
* 따라서 custom resource를 만들어주는 eck-resource라는 차트를 별도로 생성함

2021-01-27 08:29 UTC, zugwan commented
eck-operator 설치는 다른 차트로 수행되나요?

2021-01-27 08:33 UTC, zugwan requested changes

2021-01-27 08:33 UTC, zugwan commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.name" -}}
operator가 아닌 resource들에 대한 차트이므로 'eck-resource.name' 과 같은 이름은 어떨까요?

2021-01-27 08:33 UTC, zugwan commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.labels" }}
operator가 아닌 resource들에 대한 차트이므로 'eck-resource.labels' 과 같은 이름은 어떨까요?

2021-01-27 08:36 UTC, zugwan commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.name" -}}
자답입니다. decpod-base PR 내용 확인했습니다.

2021-01-28 00:13 UTC, jabbukka commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.labels" }}
좋습니다! 변경하겠습니다.

2021-01-28 00:35 UTC, jabbukka commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.name" -}}
변경했습니다.

2021-01-28 00:35 UTC, jabbukka commented on eck-resource/templates/_helpers.tpl
> +{{- define "elasticsearch-operator.labels" }}
변경했습니다.

2021-01-28 01:54 UTC, zugwan approved these changes

2021-01-28 06:35 UTC, merged