TACODEV-909: workaround for using machinepool on CAPA
openinfradev/helm-charts pull request #68
Opened 2021-08-11 02:56 UTC by intelliguy

- add job to get subnet and add a machinepool with the info

한번에 aws로 k8s 클러스터를 배포할 수 있습니다.
기존에 최종적으로 update하던 value를 처음부터 주고 돌리면 됩니다.

2021-08-11 04:37 UTC, zugwan requested changes

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/templates/job-generate-machine-pool.yaml
> +    "helm.sh/hook": post-install
machinepool 스펙 변경 (replica 수정) 등에도 동작할 수 있게 post-upgrade hook도 적용이 필요할 듯 합니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/artifacts/generate_machine_pool.py
> +  ampf.write(yaml.dump(mp['AWSMachinePool']))
MachinePool에만 적용하면 문제 없었습니다. AWSMachinePool까지 직접 설정하지 않아도 동작했었습니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/artifacts/Dockerfile
> +# COPY artifacts/generate_machine_pool.py /usr/local/bin/generate_machine_pool.py
실제 주석 용도가 아니라면 삭제하는 것이 좋을 듯 합니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/templates/job-generate-machine-pool.yaml
> +      - name: hyperkube
실제 수행하는 내용에 관련된 이름으로 변경하는 것이 좋겠습니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/templates/job-generate-machine-pool.yaml
> +        #   /generate_machine_pool.py  {{ .Values.cluster.name }} | sleep 1000
실제 주석 용도가 아니라면 삭제하는 것이 좋을 듯 합니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/values.yaml
> +# ====================================================================================================
실제 주석 용도가 아니라면 삭제하는 것이 좋을 듯 합니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/values.yaml
> +  repository: siim/test
공식 저장소에 이미지를 등록하고 사용하는 것이 좋겠습니다.

2021-08-11 04:37 UTC, zugwan commented on cluster-api-aws/values.yaml
> +  # tag: "v1.18.8"
실제 주석 용도가 아니라면 삭제하는 것이 좋을 듯 합니다.

2021-08-11 05:36 UTC, intelliguy commented on cluster-api-aws/templates/job-generate-machine-pool.yaml
> +    "helm.sh/hook": post-install
https://argoproj.github.io/argo-cd/user-guide/helm/
직접적으로는 없지만 동일하게 동작한다고 하네요.. 추가할께요.

helm.sh/hook: post-upgrade | Supported as equivalent to argocd.argoproj.io/hook: PostSync.

2021-08-11 08:34 UTC, ktkfree commented
major 수정이므로, Chart.yaml 의 version 을 0.3.1 정도로 올리는게 좋겠습니다.

2021-08-11 08:37 UTC, ktkfree commented
2step 설치가 더는 필요가 없으므로, 기존 수정분( 2step 설치 )은 모두 빼는 것이 좋겠습니다. 
그냥 두는 것이 의미가 있는지 의견주시면, 제가 이 PR merge 후 제거토록 하겠습니다.

2021-08-11 09:18 UTC, ktkfree commented on cluster-api-aws/artifacts/generate_machine_pool.py
> +  stream = os.popen('kubectl get awscluster {} -o yaml'.format(sys.argv[1]))
이 kubectl 이 바라보는 cluster 는 어디인가요? 코드 상으로는 못찾겠네요 ^^

그리고, 만약 bootstrap(k3s) cluster 라면, userCluster 생성일 경우에도 각 userCluster 생성시마다 bootstrap cluster 를 생성해주어야 할까요?

2021-08-11 09:21 UTC, zugwan commented on cluster-api-aws/artifacts/generate_machine_pool.py
> +  stream = os.popen('kubectl get awscluster {} -o yaml'.format(sys.argv[1]))
admin 클러스터입니다: Bootstrap Cluster (임시) <-> Admin Cluster <-* User Cluster

2021-08-25 00:46 UTC, Jaesang commented on cluster-api-aws/templates/kubeadm-config.yaml
> +# {{- if .Values.machinePool }}
이부분은 삭제해야할 것 같습니다.

2021-08-25 07:48 UTC, Jaesang requested changes
코드 리뷰외 추가) cluster-api-aws/templates/mt-control.yaml 이름이 Machine Template Control로 보이는데, 파일이름이 적절치 않아 보입니다.

2021-08-25 07:48 UTC, Jaesang commented on cluster-api-aws/templates/job-generate-machine-pool.yaml
> +{{- if .Values.machinePool }}
helm install 시 이 Job이 끝날때까지 계속 멈춰있는 상태입니다. async하게 바꿀 필요는 없을까요?

2021-08-25 07:48 UTC, Jaesang commented on cluster-api-aws/templates/mp/_mp.yaml
> +  MP:
MachinePool, AWSMachinePool, KubeadmConfig 값을 이렇게 MP, AMP, KCP 하위로 만들면, K8s가 어떻게 인식하나요?

2021-08-25 09:21 UTC, Jaesang commented
코멘트 달았습니다.

2021-08-27 09:11 UTC, Jaesang requested changes
helm install 시 timeout 에러가 발생하며 Job이 수행되지 않습니다.
```
$ helm install jaesang-909-2 cluster-api-aws -f cluster-api-aws/val
ues-tacodev-909.yaml
Error: failed post-install: timed out waiting for the condition
```

timeout 을 10분으로 준 뒤 실행하니 Job BackoffLimitExceeded 에러가 발생합니다.
```
$ time helm install jaesang-909-3 cluster-api-aws -f cluster-api-aw
s/values-tacodev-909.yaml --timeout 10m --debug
install.go:173: [debug] Original chart version: ""
install.go:190: [debug] CHART PATH: /home/ubuntu/helm-charts/cluster-api-aws

client.go:122: [debug] creating 8 resource(s)
client.go:122: [debug] creating 1 resource(s)
client.go:493: [debug] Watching for changes to Job jaesang-909-3-cluster-api-aws with timeout of 10m0s
client.go:521: [debug] Add/Modify event for jaesang-909-3-cluster-api-aws: ADDED
client.go:560: [debug] jaesang-909-3-cluster-api-aws: Jobs active: 0, jobs failed: 0, jobs succeeded: 0
client.go:521: [debug] Add/Modify event for jaesang-909-3-cluster-api-aws: MODIFIED
client.go:560: [debug] jaesang-909-3-cluster-api-aws: Jobs active: 1, jobs failed: 0, jobs succeeded: 0
client.go:521: [debug] Add/Modify event for jaesang-909-3-cluster-api-aws: MODIFIED
Error: failed post-install: job failed: BackoffLimitExceeded
helm.go:81: [debug] failed post-install: job failed: BackoffLimitExceeded

real    5m16.054s
user    0m0.894s
sys     0m0.322s
```
job describe
```
$ kubectl describe jobs jaesang-909-3-cluster-api-aws
Events:
  Type     Reason                Age                From            Message
  ----     ------                ----               ----            -------
  Normal   SuccessfulCreate      6m36s              job-controller  Created pod: jaesang-909-3-cluster-api-aws-w6fzm
  Normal   SuccessfulDelete      82s                job-controller  Deleted pod: jaesang-909-3-cluster-api-aws-w6fzm
  Warning  BackoffLimitExceeded  82s (x2 over 82s)  job-controller  Job has reached the specified backoff limit
```

2021-09-10 12:24 UTC, intelliguy commented
테스트 시 10분이상 돌아야 하고 defult가 5분이므로 timeout 설정을 추가해야 합니다.
--timeout=20 추가해서 배포해야 합니다.

argocd를 통한 배포시에는 timeout이내에 잘 동작함을 확인

2021-09-13 01:58 UTC, Jaesang requested changes

2021-09-13 01:58 UTC, Jaesang commented on cluster-api-aws/artifacts/wait_and_k8s_init.sh
> +  sleep 30
sleep 시간이 너무 길어 helm 설치에 소요되는 시간이 많이 깁니다.  sleep 1이나 sleep 2는 어떨까요

2021-09-13 01:58 UTC, Jaesang commented on cluster-api-aws/artifacts/wait_and_k8s_init.sh
> +  sleep 20
sleep 시간이 너무 길어 helm 설치에 소요되는 시간이 많이 깁니다.  sleep 1이나 sleep 2는 어떨까요

2021-09-13 01:58 UTC, Jaesang commented on cluster-api-aws/artifacts/wait_for_kubeconfig.sh
> +  echo "sleep 30 second"
sleep 시간이 너무 길어 helm 설치에 소요되는 시간이 많이 깁니다.  sleep 1이나 sleep 2는 어떨까요

2021-09-14 03:56 UTC, seungkyua approved these changes

2021-09-15 01:47 UTC, merged