TACODEV-909: integrate postjobs, update version and so on
openinfradev/helm-charts pull request #78
Opened 2021-09-27 08:17 UTC by intelliguy

- integrate postjobs - initialize k8s for taco and register to argocd
- change error on duplicated registration to warning
- change rbac to allow 'kubectl apply'
- update version for cluster-api-aws

2021-09-28 07:34 UTC, Jaesang requested changes

2021-09-28 07:34 UTC, Jaesang commented on cluster-api-aws/artifacts/argo-register.sh
> +    # echo "FATAL error: $1 is already registered on argo-cd server"
이전 소스 부분 남길 필요가 있을까요?

2021-09-28 07:34 UTC, Jaesang commented on cluster-api-aws/artifacts/wait_and_k8s_init.sh
> +# ./wait_and_k8s_init.sh
요 부분들도 다 삭제하시죵~

2021-10-06 03:46 UTC, intelliguy commented on cluster-api-aws/artifacts/argo-register.sh
> +    # echo "FATAL error: $1 is already registered on argo-cd server"
넵

2021-10-08 07:17 UTC, Jaesang commented on cluster-api-aws/artifacts/wait_and_k8s_init.sh
> +  while [ $(kubectl get machinepool -n $3 $1-$2-mp-0 -o=jsonpath='{.status.nodeRefs}' | wc -c) == 0 ]
데모 준비하면서 발견된 버그가 있어서, 해당 부분 적용해서 다시 올리면 좋을 거 같습니다.
(mp node가 3대가 다 되기 전에 루프를 탈출하여 2대만 label 적용됨)
참고: https://github.com/openinfradev/helm-charts/commit/70c265068d2d819adb0065463d9ec573afa4f6ad

2021-10-13 12:15 UTC, intelliguy commented on cluster-api-aws/artifacts/wait_and_k8s_init.sh
> +  while [ $(kubectl get machinepool -n $3 $1-$2-mp-0 -o=jsonpath='{.status.nodeRefs}' | wc -c) == 0 ]
추가했습니다.

2021-10-14 13:42 UTC, Jaesang approved these changes

2021-10-15 02:28 UTC, ktkfree approved these changes

2021-10-15 02:28 UTC, ktkfree commented on cluster-api-aws/templates/job-post.yaml
> +      {{- if or .Values.job.taconode.enabled .Values.job.argo.enabled  }}
아래의 argo register 를 합치신것 같은데, 굳이 .Values.job.argo.enabled 가 or 조건으로 들어갈 필요가 있을까요?

2021-10-15 02:31 UTC, intelliguy commented on cluster-api-aws/templates/job-post.yaml
> +      {{- if or .Values.job.taconode.enabled .Values.job.argo.enabled  }}
두개의 기능을 하나의 컨테이너에서 실행하도록 하면서 둘중의 하나라도 세팅되어 있으면 해당 컨테이너가 수행하도록 했습니다.
즉, 이전과 같이 

1. taconode를 초기화하는 기능과 
2. argo register를 하는 기능을

각각 사용할 수 있습니다.
이를 위한 장치입니다.

2021-10-15 03:15 UTC, merged